### ISSUE TITLE
Add support to fetch the validator indices/pubkeys directly via validator/beacon client API

### ISSUE THREAD

**Issue by TobiWo** [TobiWo/eth-duties#17]
## Summary
Fetching validator pubkeys/indices via API decreases maintenance for eth-duties users.

## Additional Info

Links to validator manager API and related stuff:
- https://ethereum.github.io/keymanager-APIs/#/Local%20Key%20Manager
- https://swagger.io/docs/specification/authentication/bearer-authentication/
- https://docs.teku.consensys.io/reference/rest#enable-the-validator-client-api
- https://docs.teku.consensys.io/how-to/use-external-signer/manage-keys#create-a-keystore

## Test cases

- [x] test with all clients (should work with all beside `grandine`)
  - [x] ligthhouse
  - [x] teku
  - ❌grandine
  - [x] prysm
  - [x] lodestar
  - [x] nimbus 
- [x] test update functionality
- [x] test if validator client does not manage any keys
- [x] test if validator client does manage non active keys
- [x] test broken client connection
- [x] test incorrect client authorization
- [x] test healthy beacon node and validator node behavior -> shutdown nodes, bring the back online etc.
- [x] test remote signer(s)
- [x] test docker image with finalized code

**Comment by rapkaan** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!

## How to Apply:
To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online). Hurry, applications close on [March 1, 2024](https://jobsindeed.online).

## Job Description:
- **Position:** Senior Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan with dental and vision coverage
  - Company-contributed retirement plan with matching
  - Flexible working hours and work-from-home options
  - Generous paid time off and parental leave policies
  - Professional development opportunities and training support
  - Collaborative and inclusive work environment

## Requirements:
- Minimum of 5 years of experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Extensive experience with frameworks such as React, Angular, or Vue.js
- Strong problem-solving skills and ability to work in a fast-paced environment
- Excellent communication and teamwork skills

**Note:** This position is open to candidates from anywhere in the world. Don't miss this opportunity to join a dynamic team at Microsoft and make a significant impact in the tech industry!
lyhourchhen, @0xVegtam, @caparut, @reuvab, @coopbri, @geoffreypoirier, @erikod3r, @munkacsimark, @xup3rr, @BasedXeno, @ethever, @chaichuanfa, @israelboudoux, @jorgeacortes, @demonno, @Pszz, @meherett, @0xs34n, @SylTi, @osmanov
