### ISSUE TITLE
Add API to add validators

### ISSUE THREAD

**Issue by laibe** [TobiWo/eth-duties#24]
This would be a nice to have feature, instead of having a static list of validators via CLI or file allow for dynamic addition of new validators via a REST API call (e.g. using [fastapi](https://fastapi.tiangolo.com/)).

**Comment by TobiWo** [comment]
Hi @laibe, I'm currently working on some smaller improvements e.g. that you can also provide pubkeys. However, the rest api feature is a great idea and was already requested multiple times (although a bit differently then you suggest, see issue link). That's tracked in the [following issue](https://github.com/TobiWo/eth-duties/issues/18). 

With regards to your proposed functionality: My idea is that `eth-duties` will read managed validator keys from the validator client itself ([see here](https://github.com/TobiWo/eth-duties/issues/17)) during runtime. All clients expose the [validator keymanager api](https://ethereum.github.io/keymanager-APIs/). So in the end the user does not need to care about supplying validators to `eth-duties` at all. However, this needs some extra configuration of the validator client itself and I'm not sure if it is an security issue to expose that api.

Maybe the best idea is to add both ways (automated fetching from client, add new indices/pubkey via POST call) so the user can decide.

**Comment by TobiWo** [comment]
I 100% agree. That's why it is probably the best way to implement both ways so more experienced users and professional node operators can decide to use the automated fetching and setting up their validator clients accordingly.
 
Yes, the authentication handling will be interesting. Need to wrap my head around this first 😃 .

**Comment by TobiWo** [comment]
HI @laibe, just for your info: The RESTful API is [now available](https://github.com/TobiWo/eth-duties/releases/tag/v0.5.0) and contains two endpoints to add and delete validator identifiers during runtime. For a full endpoint documentation please check the swagger spec which can be reached via [http://localhost:5000/docs](http://localhost:5000/docs).
