### ISSUE TITLE
Add option to pass color codes for logs

### ISSUE THREAD

**Issue by LuisNaldo7** [TobiWo/eth-duties#28]
**Issue:** 
On certain shells the default colors can make logs unreadable.

**Solution**
Provide an option (cli flag, env var, etc...) to color the logs to your needs.
Example: 
./eth-duties --log-color-warning #D2691E --log-color-critical #FF0000

**Comment by TobiWo** [comment]
I would suggest to rename the issue to `Customize log coloring`.
And add the stuff which should be done in the body, which would be:
- add customisable color codes (see your current issue description)
- add possibility to disable certain log coloring
  - disable all log colors
  - disable colors for warning and critical logs
  - disable colors for block proposer logs
  - disable colors for sync committee logs
