### ISSUE TITLE
Add compatibility for prysm, nimbus and lodestar

### ISSUE THREAD

**Issue by TobiWo** [TobiWo/eth-duties#32]
## Summary

`eth-duties` currently only supports `teku` and `lighthouse` as connected beacon clients. This should be improved.

**Comment by jabbink** [comment]
I just tested this on Prysm and it seems to work if you fix https://github.com/TobiWo/eth-duties/blob/main/duties/protocol/request.py#L162 to encapsulate the validator numbers in quotation marks

Prysm cannot decode an integer array as input and demands it to be compliant to the [specification](https://ethereum.github.io/beacon-APIs/#/Validator/getAttesterDuties) with a string array

**Comment by jabbink** [comment]
Just verified with Nimbus as well:

```sh
curl -X POST http://testing.mainnet.beacon-api.nimbus.team/eth/v1/validator/duties/attester/193011 \
    -H 'Content-Type: application/json' \
    -d '[
  1
]'
```

returns 
```json
{
    "code": 400,
    "message": "Invalid validator's index value(s)",
    "stacktraces": [
        "Unable to deserialize data"
    ]
}
```
but when queried with `["1"]`, it returns the proper attestation duties (similar to Prysms behaviour)

I can't find a publicly accessible Lodestar instance, but considering your compatibility table mentions you tested it, I assume you do. Could you, or someone else, please try sending arrays of strings on the four nodes you have access to and verify it works for Nimbus, keeps working for Lighthouse and Teku and possibly also works for Lodestar?

**Comment by TobiWo** [comment]
Hi @jabbink, thanks for reaching out and your efforts. I knew that the fix for nimbus is to send an array of strings but good to know that this is the case for prysm as well 👍 . I started implementing `eth-duties` with teku and lighthouse back in the day and those clients accept both, integers and strings which is why I got into trouble with other clients 😉 .
I already tried to send an array of strings but got some weird issues with the Python `request` library. Therefore I decided to not include this in the current release but tackle this in a separate PR with a separate release. The compatibility issue is the next point on my agenda so I will will work on this soon.

With regards to Lodestar: I didn't look into that too much so I can't say whether it is the same issue like for Nimbus and prysm but because you said the official spec refers to an array of strings it would make sense.

Best,
Tobi

**Comment by nflaig** [comment]
> With regards to Lodestar: I didn't look into that too much so I can't say whether it is the same issue like for Nimbus and prysm but because you said the official spec refers to an array of strings it would make sense.

Lodestar works with both `["1"]` and `[1]`, the problem seems to be that `Content-Type: application/json` is not set by eth-duties

**Comment by TobiWo** [comment]
@nflaig Thanks a ton :pray: . With this information and the one from @jabbink fixing all compatibility issues should be solved pretty easy. I'm currently a couple of days off but will work on that next week by the latest.

**Comment by TobiWo** [comment]
@jabbink @nflaig I fixed the compatibility issues. I tested the implementation with:

* Lighthouse
* Teku
* Nimbus
* Lodestar

I can confirm that it now works with all four clients although I had to make some specific adjustments for Lodestar. A summary can be found in the relevant PR #41.

@jabbink Can you confirm that the change also works with Prysm? I don't have a running Prysm instance currently.
The code can be found [here](https://github.com/TobiWo/eth-duties/tree/feature/improve-client-compatibility).
If you prefer docker you can find a dev image on docker: `docker pull tobiwo/eth-duties:dev-compatibility`.

Thanks a ton.

**Comment by jabbink** [comment]
Checked the PR from source on Prysm 4.0.2 synced to mainnet, and it seems to work without any local changes 👍

**Comment by nflaig** [comment]
Thanks @TobiWo for all the work! Looking forward to using this with Lodestar

**Comment by TobiWo** [comment]
@jabbink  Thanks a ton for testing.
FYI: `--validators` and `--validators-file` only differs in parsing validator identifiers for further upstream processing in `eth-duties`. Therefore if `--validators` works, `--validators-file` will also work :slightly_smiling_face: . This means the proposed update will be compatible with all consensus clients :heart_eyes: . Nice.
