### ISSUE TITLE
Fix binary for Ubuntu 20.04

### ISSUE THREAD

**Issue by jmc000** [TobiWo/eth-duties#49]
Hey, I saw in the README that you already know about that but I didn't was any issue about it.

It would be great to have a pre-build binary for Ubuntu 20.04 :)

PS: your tool is so great thanks a lot !

**Comment by TobiWo** [comment]
Hi @jmc000 , thanks for reaching out and thanks for the feedback. I really appreciate any kind of feedback but positive is of course super nice :smiley: . Will add the extra pipeline asap. I'm finalizing a new feature currently but after that I will add the new pipeline.

**Comment by TobiWo** [comment]
Hi @jmc000 , this MR will be closed now. There should be an Ubuntu 20.04 binary available when v0.4.0 gets released. Should be released in the next days.

**Comment by TobiWo** [comment]
Hi @jmc000 , the new release is out. I hope that the new binary for Ubuntu 20.04 works (I couldn't test it myself). I appreciate any reply :slightly_smiling_face: .
