### ISSUE TITLE
Colors don't seem to work

### ISSUE THREAD

**Issue by quieromibocadillo** [TobiWo/eth-duties#73]
Using Ubuntu's 22.0.4 released binary. Downloaded v0.6.0 today alongside my previous v0.4.0 installation. New version doesn't show colors when using log mode. Even when specifying the intended colors with `--log-color-warning` (BTW, documentation is wrong at https://tobiwo.github.io/eth-duties/configuration/log-colors/#note-on-hex-format since it shows `--log-time-warning` as an example and one could copy-paste without a second look).

**Comment by quieromibocadillo** [comment]
Adding a couple of screenshots:
![issue73_colors01](https://github.com/TobiWo/eth-duties/assets/162322756/c9602dcd-3daa-4166-9713-04451714729e)
![issue73_colors02](https://github.com/TobiWo/eth-duties/assets/162322756/0333d655-879b-4d7b-b187-caaff77d0a87)

**Comment by TobiWo** [comment]
Hi @quieromibocadillo,

I just tested the binary and coloring works on my Ubuntu 22.04 installation. May I ask whether you use a specific terminal? I changed the coloring package from 0.4 to 0.5 due to the fact that it wasn't possible to customize colors with the old package. However, how these packages display colors works differently. In general `sty`, which is the new package, states that it supports most unix platforms with most terminals. I tested with the default Ubuntu terminal and with [Terminator](https://github.com/gnome-terminator/terminator).

And thanks for the typo you found in the documentation :+1: . I will update that.

**Comment by quieromibocadillo** [comment]
Sorry about the late update, I was trying to see if this issue is somehow related to `pyinstaller` and some Python dinamic library that my validator system might not have installed. I even tried to create a new `sty` venv on my machine to create a hello world and give it a try, but since this is my validator system, I don't really have much installed:

```bash
# /usr/bin/python3.10 -m venv venv
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.10-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.
```
As I said, this is not really my development machine, it's the machine where the validator software is currently running, so I'm not going to install anything at all...

Anyway, getting back to your question about my environment. I'm not using anything too fancy, just the default Bash shell:

```bash
# env|grep TERM
TERM=xterm

# env|grep SHELL
SHELL=/bin/bash

# /bin/bash --version
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

I'm now guessing that it might be something related to my terminal emulator (SecureCRT 8.3.3, Windows x64). Just tried both versions of `eth-duties` from GitBash and MobaXTerm and everything looks colorful on both! 😊 I guess we can close this issue, since it seems to be an "only-me" problem.

**Comment by TobiWo** [comment]
Ah, ok, you are not on the terminal natively. I quickly googled for your terminal emulator and found indeed that it might block ansi codes. However, I'm not sure whether sty uses ansi codes for colors. Colorama, the package I used before, does use ansi codes indeed. Maybe you can check the settings of your emulator and maybe you can find a promising solution? Anyway, as you mentioned, it feels like that there is not much I can help with. 

In any case, I'm super happy that you are a user of eth-duties and hope you will continue to use it 😊. 

Best,
Tobi

**Comment by TobiWo** [comment]
Hi @quieromibocadillo,

just a short addition to may former message: Sty uses ansi codes and I found that [you need to configure SecureCRT to accept ansi codes for the session](https://www.vandyke.com/support/tips/colorconfig.html#ansicolor). As mentioned, colorama uses ansi codes as well but the default colors are different for e.g. red and yellow. So maybe SecureCRT accept some specific ansi codes out of the box but not all codes. Maybe you can try the configuration mentioned in the article. I hope this solves your issue.

Best,
Tobias

**Comment by TobiWo** [comment]
Closed as the reason for not printing colors is due to an external dependency and is therefore independent of eth-duties. I hope my hint [above](https://github.com/TobiWo/eth-duties/issues/73#issuecomment-1988008829) helps.
